name: Validate

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  hassfest:
    name: hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hacs/action@main
        with:
          category: integration
